### ISSUE TITLE
invalid URL escape  \"%2F\"

### ISSUE THREAD

**Issue by kramuenke** [honeycombio/otel-config-go#143] opened 2024-09-19 05:57 UTC
When passing an exporter endpoint including a path the config can not parse the url.

**Versions**

1.17

**Steps to reproduce**

Use a config like this:

```
otelShudown, err := otelconfig.ConfigureOpenTelemetry(
   otelconfig.WithServiceName("my-server"),
   otelconfig.WithExporterEndpoint("https://myproxy.com/otlp"),
   otelconfig.WithExporterProtocol(otelconfig.ProtocolHTTPProto),
)
```

produces the following error:

```
error: traces export: parse \"https://myproxy.com%2Fotlp/v1/traces\": invalid URL escape \"%2F\"
```

**Additional context**
We are using an http proxy to send our traces to honeycomb as we want to keep honeycomb api keys in one place.

**Comment by kramuenke** [comment] 2024-09-19 06:34
Suggestion to fix:

split the endpoint [here](https://github.com/honeycombio/otel-config-go/blob/1d6ef9aa595ca90982620b9da91c98ab78921cae/otelconfig/pipelines/trace.go#L95) when it has an extra path and use `otlptracehttp.WithURLPath`.  Or provide the same functionality via your own config.

**Comment by JamieDanielson** [comment] 2024-10-08 17:17
From what I can tell this is a duplicate of the problems described in #94 and it may require a larger change which is still on our backlog. If I have that wrong please feel free to comment on here to reopen the issue.

**Closed by JamieDanielson** 2024-10-08 17:17 UTC
Labels: type: bug, status: oncall
